# Generated by Django 3.2.7 on 2021-09-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
