# Generated by Django 3.2.7 on 2021-10-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('technologies', '0002_alter_technologies_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='Image',
            field=models.ImageField(default='images/default_software.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='Link',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='manual_EOL_date',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='Description',
            field=models.TextField(default='NA'),
        ),
    ]
