# Generated by Django 3.2.7 on 2021-10-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('technologies', '0003_auto_20211020_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='EOL_Approaching',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
