# Generated by Django 3.2.7 on 2021-10-22 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_technologies_eol_approaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='refresh_date',
            field=models.DateField(default=datetime.date(2021, 10, 22)),
        ),
    ]
