# Generated by Django 3.2.7 on 2021-10-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0005_technologies_refresh_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='refresh_date',
            field=models.DateField(default=datetime.date(2021, 10, 26)),
        ),
    ]
